### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [ChristieGuzman/prj-rev-bwfs-dasmoto#4]
Grade: **Meets Expectations**

This project is working great! I liked how your identation in your HTML was consistent as this helps understand which elements are associated with which section on the page. A couple things I would work on is making sure you add alt attributes to your images so our users have a text descriptor in the event the image doesn't load, or if they cannot identify what the image might be. Another good thing to do is to download the images and putting them inside a local resource folder in an effort to reduce future maintenance load. Next steps, I would look into learning about media queries to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries 

Nicely done!

**Comment by ChristieGuzman** [comment]
Thanks for the feedback! I'll definitely try downloading images into local resource folders in the future.
